name: Build ThingsBoard

on:
  push:
    branches:
      - master
  pull_request:
    branches:
      - master

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v2

    - name: Set up JDK 11
      uses: actions/setup-java@v2
      with:
        java-version: '11'
        distribution: 'adopt'
        cache: maven

    - name: Set up Node.js
      uses: actions/setup-node@v2
      with:
        node-version: '14'
        cache: 'npm'

    - name: Install frontend dependencies
      run: |
        cd ui-ngx
        npm install

    - name: Build frontend
      run: |
        cd ui-ngx
        npm run build

    - name: Build backend
      run: |
        mvn clean install -DskipTests

    - name: Upload build artifacts
      uses: actions/upload-artifact@v2
      with:
        name: thingsboard-build
        path: |
          application/target/*.jar
          ui-ngx/dist/*

    - name: Configure Git
      run: |
        git config --global user.email "your-email@example.com"
        git config --global user.name "your-username"

    - name: Commit changes
      run: |
        git add ui-ngx/package-lock.json
        git commit -m "Add package-lock.json"

    - name: Push changes
      env:
        GH_PAT: ${{ secrets.GH_PAT }}
      run: |
        git push https://${GH_PAT}@github.com/your-username/thingsboard-toon.git HEAD:master
