name: Build and Push Docker Image

on:
  release:
    types: [published]

jobs:
  build:
    runs-on: ubuntu-latest
    timeout-minutes: 60  # เพิ่ม timeout เพื่อให้ build มีเวลามากขึ้น

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up JDK 17
        uses: actions/setup-java@v2
        with:
          java-version: '17'
          distribution: 'adopt'

      - name: Build project
        run: |
          ./mvnw clean install -DskipTests
          mkdir -p releases
          cp application/target/*.jar releases/thingsboard.jar

      - name: Verify JAR file
        run: |
          ls -l releases
          if [ ! -f releases/thingsboard.jar ]; then echo "thingsboard.jar not found" && exit 1; fi

      - name: Copy Dockerfile
        run: cp Dockerfile releases/

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1

      - name: Login to Docker Hub
        uses: docker/login-action@v1
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      - name: Build and push Docker image
        run: |
          docker build -t your-dockerhub-username/thingsboard:v1 -f releases/Dockerfile releases
          docker push your-dockerhub-username/thingsboard:v1
