name: Build and Push Docker Image

on:
  push:
    branches:
      - master
  pull_request:
    branches:
      - master

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Download and extract release artifact
        run: |
          mkdir -p releases
          wget https://github.com/toonep06/thingsboard-toon/archive/refs/tags/v1.tar.gz -O releases/v1.tar.gz
          tar -xzf releases/v1.tar.gz -C releases
          mv releases/thingsboard-toon-1/* releases/
          rm -rf releases/thingsboard-toon-1

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1

      - name: Login to Docker Hub
        uses: docker/login-action@v1
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      - name: Build and push Docker image
        run: |
          cd ${{ github.workspace }}
          docker build -t your-dockerhub-username/thingsboard:v1 .
          docker push your-dockerhub-username/thingsboard:v1
