name: Build and Push Docker Image

on:
  release:
    types: [published]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Download and extract release artifact
        run: |
          mkdir releases
          curl -L https://github.com/toonep06/thingsboard-toon/archive/refs/tags/v1.tar.gz --output releases/v1.tar.gz
          tar -xzf releases/v1.tar.gz -C releases
          mv releases/thingsboard-toon-1/* releases/
          rm -rf releases/thingsboard-toon-1

      - name: Verify JAR file
        run: |
          dir releases
          if not exist releases\thingsboard.jar (echo "thingsboard.jar not found" && exit 1)

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1

      - name: Login to Docker Hub
        uses: docker/login-action@v1
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      - name: Build and push Docker image
        run: |
          docker build -t your-dockerhub-username/thingsboard:v1 .
          docker push your-dockerhub-username/thingsboard:v1
