name: Build and Push Docker Image

on:
  push:
    branches:
      - master
  pull_request:
    branches:
      - master

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Download and extract release artifact
        run: |
          mkdir -p releases
          curl -L https://github.com/toonep06/thingsboard-toon/archive/refs/tags/v1.tar.gz --output releases/v1.tar.gz
          tar -xzf releases/v1.tar.gz -C releases

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1

      - name: Login to Docker Hub
        uses: docker/login-action@v1
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      - name: Build and push Docker image
        run: |
          docker build -t your-dockerhub-username/thingsboard:v1 -f /thingsboard-toon-1/Dockerfile /thingsboard-toon-1
          docker push your-dockerhub-username/thingsboard:v1
