name: Build ThingsBoard

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Set up JDK 11
      uses: actions/setup-java@v2
      with:
        java-version: '11'

    - name: Set up Node.js
      uses: actions/setup-node@v2
      with:
        node-version: '14'

    - name: Install Yarn
      run: npm install -g yarn

    - name: Install Maven
      run: sudo apt-get install -y maven

    - name: Build Backend
      run: mvn clean install -DskipTests -Dlicense.skip=true

    - name: Build Frontend
      run: |
        cd ui-ngx
        yarn install
        yarn build
