name: Build ThingsBoard

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up JDK 17
        uses: actions/setup-java@v2
        with:
          distribution: 'adopt' # หรือ 'zulu' หรือ 'corretto'
          java-version: '17'

      - name: Verify Java Version
        run: java -version

      - name: Install Yarn
        run: npm install -g yarn

      - name: Install Maven
        run: sudo apt-get install -y maven

      - name: Set JAVA_HOME
        run: echo "JAVA_HOME=$(dirname $(dirname $(readlink -f $(which java))))" >> $GITHUB_ENV

      - name: Build Backend
        env:
          JAVA_HOME: ${{ env.JAVA_HOME }}
        run: mvn clean install -DskipTests -Dlicense.skip=true

      - name: Build Frontend
        run: |
          cd ui-ngx
          yarn install
          yarn build
